# fly.toml app configuration file generated for article-recommendation-system-autumn-sun-3503 on 2024-03-02T22:14:15+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'article-recommendation-system-autumn-sun-3503'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
